# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{irt}
  s.version = "0.7.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Domizio Demichelis"]
  s.date = %q{2010-09-23}
  s.default_executable = %q{irt}
  s.description = %q{IRT records and rerun the steps of your interactive irb or rails console session, ignoring the inspecting commands and reporting test diffs. }
  s.email = %q{dd.nexus@gmail.com}
  s.executables = ["irt"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/irt",
     "examples/objects.irt",
     "irt.gemspec",
     "lib/irt.rb",
     "lib/irt/differ.rb",
     "lib/irt/directives.rb",
     "lib/irt/directives/core.rb",
     "lib/irt/directives/history.rb",
     "lib/irt/directives/system.rb",
     "lib/irt/directives/test.rb",
     "lib/irt/extensions.rb",
     "lib/irt/history.rb",
     "lib/irt/init.rb",
     "lib/irt/irb.rb"
  ]
  s.homepage = %q{http://github.com/ddnexus/irt}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Interactive Ruby Testing - Use irb or rails console for testing.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<differ>, [">= 0.1.1"])
      s.add_runtime_dependency(%q<colorer>, [">= 0.2.0"])
    else
      s.add_dependency(%q<differ>, [">= 0.1.1"])
      s.add_dependency(%q<colorer>, [">= 0.2.0"])
    end
  else
    s.add_dependency(%q<differ>, [">= 0.1.1"])
    s.add_dependency(%q<colorer>, [">= 0.2.0"])
  end
end

